[project]
name = "sogc-tracker"
version = "0.1.0"
description = "SOGC Tracker"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "requests>=2.32.5"
]

[project.scripts]
sogc-tracker = "sogc_tracker.main:main"